### PR TITLE
Store context instead of span only

### PR DESCRIPTION
**Pull request by duxet**
We should store entire Context in FiberRef instead of span, so we don't lose things like [https://w3c.github.io/baggage/](Baggage) when we propagate context to other services.

This change shouldn't break the existing API.

### CODE REVIEW

**Review by easel — APPROVED** [review]
LGTM

**Review by runtologist — APPROVED** [review]

**Comment by runtologist** [comment]
Great. Thank you for this contribution. LGTM.

**Comment by runtologist** [comment]
Good to merge once merge conflicts have been resolved.

**Comment by duxet** [comment]
@easel @runtologist Could you take a look at this PR again, please? I've merged it with master branch.

**Pull request merged**
