### PR TITLE
Support setting attributes when creating a span

### PR DESCRIPTION
**Pull request by davidlar**
I need to create a sampler that decides if it should sample or not based on a http header. As I understand the otel documentation, it should be done with attributes and those attributes needs to be set when the span is created.

### CODE REVIEW

**Comment by grouzen** [comment]
Some compilation errors need to be fixed:
```
error] /home/runner/work/zio-telemetry/zio-telemetry/opentelemetry/src/main/scala/zio/telemetry/opentelemetry/tracing/Tracing.scala:732:13: private default argument in <$anon: zio.telemetry.opentelemetry.tracing.Tracing> is never used
[error]             attributes: Attributes = Attributes.empty(),
[error]             ^
```
Otherwise, I'm glad to approve it! 
Thanks for your contribution!

**Review by grouzen — DISMISSED** [review]

**Comment by grouzen** [comment]
We have some issues with sbt-zio-website plugin so in order to make CI happy you need to run `sbt docs/generateReadme` in your branch. Sorry for this.

**Comment by davidlar** [comment]
No problem! I pushed again now. Let's hope for success! :-)

**Comment by grouzen** [comment]
Sorry for this inconvenience. It is a bit annoying. I'm trying to fix this in this PR: https://github.com/zio/zio-telemetry/pull/661

**Comment by davidlar** [comment]
Great! Thanks! Yes I'm a bit lost :)

**Comment by grouzen** [comment]
Please, try to run generateReadme one more time. Now we've got an issue with badges :disappointed:

**Comment by davidlar** [comment]
A walk in the park! :smiley:

**Review by grouzen — APPROVED** [review]

**Comment by grouzen** [comment]
Thanks! Good job. I'm merging it and will cut another RC release for you.

**Comment by davidlar** [comment]
Many thanks! :smiley:

**Pull request merged**
