### PR TITLE
ZIO-2.0.0-RC4

### PR DESCRIPTION
**Pull request by vladimir-lu**

### CODE REVIEW

**Comment by runtologist** [comment]
Thanks a lot for this upgrade @vladimir-lu. `sbt compileExamples` is still failing. Would you mind taking a look at that?

**Comment by vladimir-lu** [comment]
Should be good now. I think `ZIO.scoped` acts a little bit differently in type inference compared to `ZManaged` but overall it does seem to be a good simplification.

Would you be able to cut a release after this is merged?

**Review by runtologist — APPROVED** [review]
LGTM

**Comment by runtologist** [comment]
> Should be good now. I think `ZIO.scoped` acts a little bit differently in type inference compared to `ZManaged` but overall it does seem to be a good simplification.

Yes, I found in a few places it needs type annotations, where ZManaged didn't.

Thanks again for the upgrade. 

> Would you be able to cut a release after this is merged?

I'll do.

**Pull request merged**
