### PR TITLE
OpenTracing - Add noop tracing

### PR DESCRIPTION
**Pull request by Fristi**
Useful for testing! If approved/merged could you release a 0.1.1 version ? :)

### CODE REVIEW

**Comment by runtologist** [comment]
Thank you for your contribution, @fristi 🙏. This is useful indeed. Could you please sign the CLA by clicking the link in the CLAassistant comment above?

**Comment by Fristi** [comment]
I already signed it, but it says 

> You have signed the CLA already but the status is still pending? Let us recheck it.

Pressed recheck a few times, but still it's pending 🤷‍♂

**Comment by runtologist** [comment]
Could the reason be that you commented as @Fristi but commited as @mark-dhl?

**Comment by Fristi** [comment]
Should be fixed now

**Pull request merged**
